- hosts: all
  become: true
  tasks: 
     - name: delete old deployment
       command: kubectl delete -f /home/ubuntu/build/getting-started/Deployment.yml       
     - name: delete old service
       command: kubectl delete -f /home/ubuntu/build/getting-started/Service.yml       
     - name: create new deployment
       command: kubectl apply -f /home/ubuntu/build/getting-started/Deployment.yml
     - name: create new service
       command: kubectl apply -f /home/ubuntu/build/getting-started/Service.yml       
