- hosts: all
  become: true
  tasks: 
     - name: delete old deployment
       shell: kubectl delete -f /home/ubuntu/build/getting-started/Deployment.yml
       args:
        executable: /bin/bash
     - name: delete old service
       shell: kubectl delete -f /home/ubuntu/build/getting-started/Service.yml
       args:
        executable: /bin/bash
     - name: create new deployment
       shell: kubectl apply -f /home/ubuntu/build/getting-started/Deployment.yml
       args:
        executable: /bin/bash
     - name: create new service
       shell: kubectl apply -f /home/ubuntu/build/getting-started/Service.yml
       args:
        executable: /bin/bash
