kind: Service                             
apiVersion: v1
metadata:
  name: getting-started
  labels:
    app: getting-started
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: getting-started                    
  type: LoadBalancer                   
